version: '3.8'

services:
  # Banco de Dados PostgreSQL
  postgres:
    image: postgres:15
    container_name: ufpi_ic_api_postgres
    environment:
      POSTGRES_DB: ufpi_ic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ufpi_ic"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Flask
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ufpi_ic_api
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/venv
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - api_network
    restart: unless-stopped

networks:
  api_network:
    driver: bridge

volumes:
  postgres_data: 