version: '3.8'

services:
  # API Flask para produção (conecta com banco externo)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auto_correction_api
    environment:
      # Essas variáveis serão definidas no Render ou via .env
      - FLASK_ENV=${FLASK_ENV:-production}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS:-}
      - PORT=${PORT:-5000}
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    restart: unless-stopped
    command: python app.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-5000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Nota: Para desenvolvimento local com banco, use:
# docker-compose -f docker-compose.dev.yml up --build 